In [1]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import SimpleRNN

In [2]:
# preparing independent and dependent features
def prepare_data(timeseries_data, n_features):
    X, y =[],[]
    for i in range(len(timeseries_data)):
        # find the end of this pattern
        end_ix = i + n_features
        # check if we are beyond the sequence
        if end_ix > len(timeseries_data)-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = timeseries_data[i:end_ix], timeseries_data[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

In [3]:
# define input sequence
timeseries_data = [110, 125, 133, 146, 158, 172, 187, 196, 210]

In [4]:
# choose a number of time steps
n_steps = 3

In [5]:
# split into samples
X, y = prepare_data(timeseries_data, n_steps)

print(X),print(y)

[[110 125 133]
 [125 133 146]
 [133 146 158]
 [146 158 172]
 [158 172 187]
 [172 187 196]]
[146 158 172 187 196 210]


(None, None)

In [6]:
X.shape

(6, 3)

In [7]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

In [8]:
# define model
model = Sequential()
model.add(SimpleRNN(50, activation='relu', return_sequences=True, input_shape=(n_steps, n_features)))
model.add(SimpleRNN(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [9]:
# fit model
model.fit(X, y, epochs=300, verbose=1)

Epoch 1/300
1/1 [==============================] - 3s 3s/step - loss: 24657.3340
Epoch 2/300
1/1 [==============================] - 0s 12ms/step - loss: 19900.2324
Epoch 3/300
1/1 [==============================] - 0s 13ms/step - loss: 15979.1201
Epoch 4/300
1/1 [==============================] - 0s 15ms/step - loss: 12644.8516
Epoch 5/300
1/1 [==============================] - 0s 12ms/step - loss: 9918.5713
Epoch 6/300
1/1 [==============================] - 0s 12ms/step - loss: 7585.6113
Epoch 7/300
1/1 [==============================] - 0s 13ms/step - loss: 5551.3745
Epoch 8/300
1/1 [==============================] - 0s 13ms/step - loss: 3916.6648
Epoch 9/300
1/1 [==============================] - 0s 13ms/step - loss: 2607.7322
Epoch 10/300
1/1 [==============================] - 0s 15ms/step - loss: 1563.9137
Epoch 11/300
1/1 [==============================] - 0s 15ms/step - loss: 794.0430
Epoch 12/300
1/1 [==============================] - 0s 14ms/step - loss: 293.6920
Epoch 13/300


1/1 [==============================] - 0s 8ms/step - loss: 14.0315
Epoch 103/300
1/1 [==============================] - 0s 7ms/step - loss: 13.9686
Epoch 104/300
1/1 [==============================] - 0s 9ms/step - loss: 13.9309
Epoch 105/300
1/1 [==============================] - 0s 9ms/step - loss: 13.9191
Epoch 106/300
1/1 [==============================] - 0s 9ms/step - loss: 13.9287
Epoch 107/300
1/1 [==============================] - 0s 10ms/step - loss: 13.9516
Epoch 108/300
1/1 [==============================] - 0s 9ms/step - loss: 13.9786
Epoch 109/300
1/1 [==============================] - 0s 11ms/step - loss: 14.0013
Epoch 110/300
1/1 [==============================] - 0s 9ms/step - loss: 14.0139
Epoch 111/300
1/1 [==============================] - 0s 11ms/step - loss: 14.0138
Epoch 112/300
1/1 [==============================] - 0s 10ms/step - loss: 14.0019
Epoch 113/300
1/1 [==============================] - 0s 10ms/step - loss: 13.9816
Epoch 114/300
1/1 [==================

1/1 [==============================] - 0s 9ms/step - loss: 13.7709
Epoch 203/300
1/1 [==============================] - 0s 8ms/step - loss: 13.7691
Epoch 204/300
1/1 [==============================] - 0s 9ms/step - loss: 13.7674
Epoch 205/300
1/1 [==============================] - 0s 11ms/step - loss: 13.7656
Epoch 206/300
1/1 [==============================] - 0s 11ms/step - loss: 13.7637
Epoch 207/300
1/1 [==============================] - 0s 11ms/step - loss: 13.7621
Epoch 208/300
1/1 [==============================] - 0s 10ms/step - loss: 13.7604
Epoch 209/300
1/1 [==============================] - 0s 10ms/step - loss: 13.7586
Epoch 210/300
1/1 [==============================] - 0s 9ms/step - loss: 13.7569
Epoch 211/300
1/1 [==============================] - 0s 9ms/step - loss: 13.7551
Epoch 212/300
1/1 [==============================] - 0s 10ms/step - loss: 13.7533
Epoch 213/300
1/1 [==============================] - 0s 7ms/step - loss: 13.7515
Epoch 214/300
1/1 [=================

In [10]:
# demonstrate prediction for next 10 days
x_input = np.array([187, 196, 210])
temp_input=list(x_input)
lst_output=[]
i=0
while(i<10):
    
    if(len(temp_input)>3):
        x_input = np.array(temp_input[1:])
        print("{} day input {}".format(i,x_input))
        #print(x_input)
        x_input = x_input.reshape((1, n_steps, n_features))
        #print(x_input)
        yhat = model.predict(x_input, verbose=0)
        print("{} day output {}".format(i,yhat))
        temp_input.append(yhat[0][0])
        temp_input=temp_input[1:]
        #print(temp_input)
        lst_output.append(yhat[0][0])
        i=i+1
    else:
        x_input = x_input.reshape((1, n_steps, n_features))
        yhat = model.predict(x_input, verbose=0)
        print(yhat[0])
        temp_input.append(yhat[0][0])
        lst_output.append(yhat[0][0])
        i=i+1
    

[228.88193]
1 day input [196.         210.         228.88192749]
1 day output [[244.59555]]
2 day input [210.         228.88192749 244.59555054]
2 day output [[264.68536]]
3 day input [228.88193 244.59555 264.68536]
3 day output [[284.71884]]
4 day input [244.59555 264.68536 284.71884]
4 day output [[306.89563]]
5 day input [264.68536 284.71884 306.89563]
5 day output [[330.68307]]
6 day input [284.71884 306.89563 330.68307]
6 day output [[356.23752]]
7 day input [306.89563 330.68307 356.23752]
7 day output [[383.85715]]
8 day input [330.68307 356.23752 383.85715]
8 day output [[413.54584]]
9 day input [356.23752 383.85715 413.54584]
9 day output [[445.56052]]


In [11]:
#next 10 predicted values are:
print(lst_output)

[228.88193, 244.59555, 264.68536, 284.71884, 306.89563, 330.68307, 356.23752, 383.85715, 413.54584, 445.56052]
